[package]
name = "collision_simulator"
version = "0.1.0"
edition = "2021"             # Change from "2024" to "2021"

[dependencies]
raylib = "5.0"
engine_core = { path = "../engine_core" }
rand = "0.8"
